spring:
  application:
    name: Bookzindaclub
  datasource:
    url: jdbc:postgresql://project2db.c36ta8kttd49.us-east-1.rds.amazonaws.com:5432/project2db
    username: fdetorres
    password: p4ssw0rd
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbcUrl: url
server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web: DEBUG
